version: '3.4'

services:
  mongo-database:
    image: "mongo:latest"
  mircoservice:
    image: mircoservice
    build:
      context: node-mircoservice
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - mongo-database
    links:
      - mongo-database
    expose:
      - 8000
    ports:
      - 8000:8000
  chartapp:
    image: chartapp
    build:
      context: next-fe-microservice/chart-app
      dockerfile: Dockerfile
    depends_on:
      - mircoservice
    links:
      - mircoservice
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
