version: '3.4'

services:
  mongo-database:
    image: "mongo:latest"
  mircoservice:
    image: mircoservice
    build:
      context: ./node-mircoservice/
      dockerfile: ./node-mircoservice/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
      - 9229:9229
    command: [ "node", "--inspect=0.0.0.0:9229", "server.js" ]
  chartapp:
    image: chartapp
    build:
      context: ./next-fe-microservice/chart-app/
      dockerfile: ./next-fe-microservice/chart-app/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: [ "node", "--inspect=0.0.0.0:9229", "index.js" ]
